export const ACTIONS_1D = {
  CHANGE_SEQUENCE: 'CHANGE_SEQUENCE',

  CHANGE_TM: 'CHANGE_TM',
  CHANGE_PRMLEN: 'CHANGE_PRMLEN',
  CHANGE_NUMPRM: 'CHANGE_NUMPRM',
  CHANGE_T7CHK: 'CHANGE_T7CHK',

  CLEANUP_1D: 'CLEANUP_1D'
};

export const ACTIONS_2D = {
  CHANGE_SEQUENCE: 'CHANGE_SEQUENCE',

  CHANGE_PRIMER: 'CHANGE_PRIMER',
  ADD_PRIMER: 'ADD_PRIMER',

  CHANGE_OFFSET: 'CHANGE_OFFSET',
  CHANGE_STARTPOS: 'CHANGE_STARTPOS',
  CHANGE_ENDPOS: 'CHANGE_ENDPOS',
  CHANGE_LIBOPT: 'CHANGE_LIBOPT',

  CLEANUP_2D: 'CLEANUP_2D'
};

