export const ACTIONS_1D = {
  CHANGE_TAG: 'CHANGE_TAG',
  CHANGE_SEQUENCE: 'CHANGE_SEQUENCE',

  CHANGE_TM: 'CHANGE_TM',
  CHANGE_PRMLEN: 'CHANGE_PRMLEN',
  CHANGE_NUMPRM: 'CHANGE_NUMPRM',
  CHANGE_T7CHK: 'CHANGE_T7CHK',

  CLEANUP: 'CLEANUP',
  RESET: 'RESET'
};

export const ACTIONS_2D = {
  CHANGE_TAG: 'CHANGE_TAG',
  CHANGE_SEQUENCE: 'CHANGE_SEQUENCE',

  CHANGE_PRIMER: 'CHANGE_PRIMER',
  ADD_PRIMER: 'ADD_PRIMER',
  REMOVE_PRIMER: 'REMOVE_PRIMER',

  CHANGE_OFFSET: 'CHANGE_OFFSET',
  CHANGE_REGPOS: 'CHANGE_REGPOS',
  CHANGE_LIBOPT: 'CHANGE_LIBOPT',

  DRAW_ILLUSTRATION: 'DRAW_ILLUSTRATION',
  STOP_ILLUSTRATION: 'STOP_ILLUSTRATION',

  CLEANUP: 'CLEANUP',
  RESET: 'RESET'
};

