export const ACTIONS_1D = {
  CHANGE_TAG: 'CHANGE_1D_TAG',
  CHANGE_SEQUENCE: 'CHANGE_1D_SEQUENCE',

  CHANGE_TM: 'CHANGE_1D_TM',
  CHANGE_PRMLEN: 'CHANGE_1D_PRMLEN',
  CHANGE_NUMPRM: 'CHANGE_1D_NUMPRM',
  CHANGE_T7CHK: 'CHANGE_1D_T7CHK',

  CLEANUP: 'CLEANUP_1D',
  RESET: 'RESET_1D',
  SUBMIT: 'SUBMIT_1D'
};

export const ACTIONS_2D = {
  CHANGE_TAG: 'CHANGE_2D_TAG',
  CHANGE_SEQUENCE: 'CHANGE_2D_SEQUENCE',

  CHANGE_PRIMER: 'CHANGE_2D_PRIMER',
  ADD_PRIMER: 'ADD_2D_PRIMER',
  REMOVE_PRIMER: 'REMOVE_2D_PRIMER',

  CHANGE_OFFSET: 'CHANGE_2D_OFFSET',
  CHANGE_REGPOS: 'CHANGE_2D_REGPOS',
  CHANGE_LIBOPT: 'CHANGE_2D_LIBOPT',

  DRAW_ILLUSTRATION: 'DRAW_2D_ILLUSTRATION',
  STOP_ILLUSTRATION: 'STOP_2D_ILLUSTRATION',

  CLEANUP: 'CLEANUP_2D',
  RESET: 'RESET_2D'
};


export const ACTIONS_RESULT = {
  CLEAR: 'CLEAR_RESULT'
};
